### ISSUE TITLE
AttributeError: 'BertConfig' object has no attribute 'label2id'

### ISSUE THREAD

**Issue by qiutzh** [kelvincjr/myRepo#1]
@kelvincjr 
```shell
#modeling/ner/trainer.py
class BertCrfForNer(BertPreTrainedModel):
    def __init__(self, config):
        super(BertCrfForNer, self).__init__(config)
        #  self.num_labels = len(label2id)

        self.num_labels = config.num_labels
        self.crf_type = config.crf_type
        self.no_crf_loss = config.no_crf_loss
        self.loss_type = config.loss_type
        self.focalloss_gamma = config.focalloss_gamma
        self.focalloss_alpha = config.focalloss_alpha
        self.diceloss_weight = config.diceloss_weight

        self.bert = BertModel(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size, self.num_labels)

        label2id = config.label2id   # 执行到此处报错
        ...
```
另外，尝试运行CCKS2020的事件属性抽取脚本 run_event_element.py 时，也报了类似错误
```shell
Traceback (most recent call last):
  File "/home/ll/ee/run_event_element.py", line 921, in <module>
    main(args)
  File "/home/ll/ee/run_event_element.py", line 873, in main
    do_train(args)
  File "/home/ll/ee/run_event_element.py", line 855, in do_train
    trainer.train(args, train_examples, val_examples)
  File "/home/ll/ee/theta/modeling/trainer.py", line 181, in train
    model, optimizer, scheduler = self.build_model(args)
  File "/home/ll/ee/theta/modeling/ner/trainer.py", line 527, in build_default_model
    model = load_pretrained_model(args)
  File "/home/ll/ee/theta/modeling/ner/trainer.py", line 478, in load_pretrained_model
    cache_dir=args.cache_dir if args.cache_dir else None,
  File "/opt/Miniconda3/envs/py3/lib/site-packages/transformers/modeling_utils.py", line 398, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() missing 2 required positional arguments: 'label2id' and 'device'
```

请问，要怎么修改呀？

**Comment by qiutzh** [comment]
问题已解决~
